name = "REPL"
defaultTargets = ["repl", "corpus"]

[[lean_lib]]
name = "REPL"

[[lean_exe]]
name = "repl"
root = "REPL.Main"
supportInterpreter = true

[[lean_exe]]
name = "corpus"
root = "Corpus"
supportInterpreter = true
